### ISSUE TITLE
[Snowflake] `dbt compile` throws `memory exception for ffi.callback()` on M1 Macbook Air 

### ISSUE THREAD

**Issue by jplynch77** [dbt-labs/dbt-snowflake#19]
### Describe the bug
This is basically dbt-labs/dbt#3162, but I'm still running into the problem with `send_anonymous_usage_stats: False` as well as trying the `0.21.0-b1` prerelease version where this `anonymous_usage` issue is patched. `dbt compile` and `dbt run` both throw `MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks`. 

### Steps To Reproduce
On a 2020 Macbook Air running Big Sur 11.5. Installed `dbt` as follows
```
brew install python
python3 -m venv dbt-env  
source dbt-env/bin/activate  
pip install dbt
```
dbt installs fine with either version, and `dbt -version` works fine as well. However when I do `dbt compile` or `dbt run` I run into the `ffi.callback() error`. I got this error with both `0.20.0` and `0.21.0-b1`.

I know there was an attempted fix as described in [this comment](https://github.com/dbt-labs/dbt/issues/3162#issuecomment-890031125) but I think that only addresses the case where this is affecting anonymous tracking and the problem here seems to be with the primary `snowflake-connector-python` connection to Snowflake (see trace below). 

There is also an [open issue](https://github.com/snowflakedb/snowflake-connector-python/issues/799#issue-948711519) on `snowflake-connector-python` repo but no progress towards fixing that yet. 
 
### Expected behavior
`dbt compile` and `dbt run` run without error. 

### Screenshots and log output
Full trace.

```
    show terse objects in user_scratch.jlynch_dbt
2021-08-11 02:38:15.323454 (ThreadPoolExecutor-0_0): Rolling back transaction.
2021-08-11 02:38:15.323576 (ThreadPoolExecutor-0_1): Rolling back transaction.
2021-08-11 02:38:15.323678 (ThreadPoolExecutor-0_0): Opening a new connection, currently in state init
2021-08-11 02:38:15.323817 (ThreadPoolExecutor-0_1): Opening a new connection, currently in state init
2021-08-11 02:38:15.423470 (ThreadPoolExecutor-0_1): Error running SQL: macro list_relations_without_caching
2021-08-11 02:38:15.423695 (ThreadPoolExecutor-0_1): Rolling back transaction.
2021-08-11 02:38:15.424342 (ThreadPoolExecutor-0_1): Opening a new connection, currently in state init
2021-08-11 02:38:15.424882 (ThreadPoolExecutor-0_0): Error running SQL: macro list_relations_without_caching
2021-08-11 02:38:15.426007 (ThreadPoolExecutor-0_0): Rolling back transaction.
2021-08-11 02:38:15.426822 (ThreadPoolExecutor-0_0): Opening a new connection, currently in state init
2021-08-11 02:38:15.535091 (MainThread): Connection 'master' was properly closed.
2021-08-11 02:38:15.535311 (MainThread): Connection 'list_analytics_snapshot' was properly closed.
2021-08-11 02:38:15.535435 (MainThread): Connection 'list_user_scratch_jlynch_dbt' was properly closed.
2021-08-11 02:38:15.535643 (MainThread): Flushing usage events
2021-08-11 02:38:15.535784 (MainThread): Encountered an error:
2021-08-11 02:38:15.535869 (MainThread): Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks
2021-08-11 02:38:15.538470 (MainThread): Traceback (most recent call last):
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/dbt/adapters/snowflake/connections.py", line 179, in exception_handler
    yield
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/dbt/adapters/sql/connections.py", line 79, in add_query
    cursor = connection.handle.cursor()
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/dbt/contracts/connection.py", line 81, in handle
    self._handle.resolve(self)
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/dbt/contracts/connection.py", line 107, in resolve
    return self.opener(connection)
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/dbt/adapters/snowflake/connections.py", line 220, in open
    handle = snowflake.connector.connect(
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/snowflake/connector/__init__.py", line 50, in Connect
    return SnowflakeConnection(**kwargs)
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/snowflake/connector/connection.py", line 273, in __init__
    self.connect(**kwargs)
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/snowflake/connector/connection.py", line 484, in connect
    self.__open_connection()
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/snowflake/connector/connection.py", line 723, in __open_connection
    self._authenticate(auth_instance)
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/snowflake/connector/connection.py", line 984, in _authenticate
    self.__authenticate(self.__preprocess_auth_instance(auth_instance))
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/snowflake/connector/connection.py", line 1003, in __authenticate
    auth.authenticate(
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/snowflake/connector/auth.py", line 241, in authenticate
    ret = self._rest._post_request(
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/snowflake/connector/network.py", line 629, in _post_request
    ret = self.fetch(
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/snowflake/connector/network.py", line 719, in fetch
    ret = self._request_exec_wrapper(
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/snowflake/connector/network.py", line 841, in _request_exec_wrapper
    raise e
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/snowflake/connector/network.py", line 762, in _request_exec_wrapper
    return_object = self._request_exec(
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/snowflake/connector/network.py", line 1049, in _request_exec
    raise err
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/snowflake/connector/network.py", line 926, in _request_exec
    raw_ret = session.request(
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/snowflake/connector/vendored/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/snowflake/connector/vendored/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/snowflake/connector/vendored/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/snowflake/connector/vendored/urllib3/connection.py", line 392, in connect
    self.ssl_context = create_urllib3_context(
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/snowflake/connector/vendored/urllib3/util/ssl_.py", line 339, in create_urllib3_context
    context.verify_mode = cert_reqs
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/snowflake/connector/vendored/urllib3/contrib/pyopenssl.py", line 444, in verify_mode
    self._ctx.set_verify(_stdlib_to_openssl_verify[value], _verify_callback)
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/OpenSSL/SSL.py", line 1028, in set_verify
    self._verify_helper = _VerifyHelper(callback)
  File "/Users/john.lynch/dbt-env/lib/python3.9/site-packages/OpenSSL/SSL.py", line 331, in __init__
    self.callback = _ffi.callback(
MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.20.0
   latest version: 0.20.0

Up to date!

Plugins:
  - snowflake: 0.20.0
```

**The operating system you're using:**
MacOS Big Sur 11.5

**The output of `python --version`:**
Python 3.9.6

**Comment by bpmcd** [comment]
Instead of the workaround above (installing Homebrew via Rosetta), I customized a docker image based on this image https://hub.docker.com/r/xemuliam/dbt. Docker Desktop now natively supports M1 architectures, and this image can build arm64 Linux containers that do not exhibit the FFI issue.
