### ISSUE TITLE
[ADAP-716] [Bug] When previewing leading zero dates, we run into an error Failed to convert current row, cause: ordinal must be >= 1

### ISSUE THREAD

**Issue by jeremyyeo** [dbt-labs/dbt-snowflake#700]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

If a table in Snowflake has a `DATE` column with leading zeros, we run into an error. This is directly related to: https://github.com/snowflakedb/snowflake-connector-python/issues/1652

### Expected Behavior

I think we may want to handle this more gracefully from the adapter end?

### Steps To Reproduce

1. Create a model with leading zero dates.

```sql
-- models/foo.sql
select '0000-12-30'::date as date_with_zeros
```

2. Try previewing:

```sh
$ dbt show -s foo
23:29:31  Running with dbt=1.5.3
23:29:33  Registered adapter: snowflake=1.5.2
23:29:35  Found 38 models, 0 tests, 0 snapshots, 0 analyses, 387 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
23:29:35  
23:29:38  Concurrency: 1 threads (target='default')
23:29:38  
23:29:41  Unhandled error while executing 
252005: Failed to convert current row, cause: ordinal must be >= 1
23:29:41  Encountered an error:
Runtime Error
  252005: Failed to convert current row, cause: ordinal must be >= 1
```

### Relevant log output

```shell
23:29:59  Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1086d1a20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109f96020>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109f96170>]}
23:29:59  Running with dbt=1.5.3
23:29:59  running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'False', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'True', 'log_path': '/Users/jeremy/src/dbt-sandcastles/dbt/snowflake/logs', 'version_check': 'True', 'profiles_dir': '/Users/jeremy/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
23:30:00  Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '0bee3779-05e7-457f-a0f5-bea7b7fbf704', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109f96200>]}
23:30:00  Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '0bee3779-05e7-457f-a0f5-bea7b7fbf704', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11baf9840>]}
23:30:00  Registered adapter: snowflake=1.5.2
23:30:01  checksum: d91324b50612e0c4823cec6657ec795d80c11aba9d5b50e83fb26de63277dec4, vars: {}, profile: , target: , version: 1.5.3
23:30:01  Partial parsing not enabled
23:30:02  1699: static parser successfully parsed qux.sql
23:30:02  1699: static parser successfully parsed foo.sql
23:30:02  1603: static parser failed on baz.sql
23:30:02  1602: parser fallback to jinja rendering on baz.sql
23:30:02  1699: static parser successfully parsed bar.sql
23:30:02  1699: static parser successfully parsed fct_dbt__invocations.sql
23:30:02  1699: static parser successfully parsed fct_dbt__seed_executions.sql
23:30:02  1699: static parser successfully parsed dim_dbt__tests.sql
23:30:02  1699: static parser successfully parsed fct_dbt__test_executions.sql
23:30:02  1699: static parser successfully parsed dim_dbt__snapshots.sql
23:30:02  1603: static parser failed on fct_dbt__model_executions.sql
23:30:02  1602: parser fallback to jinja rendering on fct_dbt__model_executions.sql
23:30:02  1699: static parser successfully parsed dim_dbt__sources.sql
23:30:02  1603: static parser failed on dim_dbt__current_models.sql
23:30:02  1602: parser fallback to jinja rendering on dim_dbt__current_models.sql
23:30:02  1699: static parser successfully parsed dim_dbt__exposures.sql
23:30:02  1699: static parser successfully parsed dim_dbt__models.sql
23:30:02  1699: static parser successfully parsed fct_dbt__snapshot_executions.sql
23:30:02  1699: static parser successfully parsed dim_dbt__seeds.sql
23:30:02  1603: static parser failed on staging/stg_dbt__snapshot_executions.sql
23:30:02  1602: parser fallback to jinja rendering on staging/stg_dbt__snapshot_executions.sql
23:30:02  1603: static parser failed on staging/stg_dbt__models.sql
23:30:02  1602: parser fallback to jinja rendering on staging/stg_dbt__models.sql
23:30:02  1699: static parser successfully parsed staging/stg_dbt__invocations.sql
23:30:02  1603: static parser failed on staging/stg_dbt__seeds.sql
23:30:03  1602: parser fallback to jinja rendering on staging/stg_dbt__seeds.sql
23:30:03  1603: static parser failed on staging/stg_dbt__snapshots.sql
23:30:03  1602: parser fallback to jinja rendering on staging/stg_dbt__snapshots.sql
23:30:03  1603: static parser failed on staging/stg_dbt__exposures.sql
23:30:03  1602: parser fallback to jinja rendering on staging/stg_dbt__exposures.sql
23:30:03  1603: static parser failed on staging/stg_dbt__test_executions.sql
23:30:03  1602: parser fallback to jinja rendering on staging/stg_dbt__test_executions.sql
23:30:03  1603: static parser failed on staging/stg_dbt__sources.sql
23:30:03  1602: parser fallback to jinja rendering on staging/stg_dbt__sources.sql
23:30:03  1603: static parser failed on staging/stg_dbt__tests.sql
23:30:03  1602: parser fallback to jinja rendering on staging/stg_dbt__tests.sql
23:30:03  1603: static parser failed on staging/stg_dbt__seed_executions.sql
23:30:03  1602: parser fallback to jinja rendering on staging/stg_dbt__seed_executions.sql
23:30:03  1603: static parser failed on staging/stg_dbt__model_executions.sql
23:30:03  1602: parser fallback to jinja rendering on staging/stg_dbt__model_executions.sql
23:30:03  1603: static parser failed on sources/exposures.sql
23:30:03  1602: parser fallback to jinja rendering on sources/exposures.sql
23:30:03  1603: static parser failed on sources/snapshot_executions.sql
23:30:03  1602: parser fallback to jinja rendering on sources/snapshot_executions.sql
23:30:03  1603: static parser failed on sources/test_executions.sql
23:30:03  1602: parser fallback to jinja rendering on sources/test_executions.sql
23:30:03  1603: static parser failed on sources/invocations.sql
23:30:03  1602: parser fallback to jinja rendering on sources/invocations.sql
23:30:03  1603: static parser failed on sources/seed_executions.sql
23:30:03  1602: parser fallback to jinja rendering on sources/seed_executions.sql
23:30:03  1603: static parser failed on sources/seeds.sql
23:30:03  1602: parser fallback to jinja rendering on sources/seeds.sql
23:30:03  1603: static parser failed on sources/models.sql
23:30:03  1602: parser fallback to jinja rendering on sources/models.sql
23:30:03  1603: static parser failed on sources/sources.sql
23:30:03  1602: parser fallback to jinja rendering on sources/sources.sql
23:30:03  1603: static parser failed on sources/snapshots.sql
23:30:03  1602: parser fallback to jinja rendering on sources/snapshots.sql
23:30:03  1603: static parser failed on sources/model_executions.sql
23:30:03  1602: parser fallback to jinja rendering on sources/model_executions.sql
23:30:03  1603: static parser failed on sources/tests.sql
23:30:03  1602: parser fallback to jinja rendering on sources/tests.sql
23:30:04  Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '0bee3779-05e7-457f-a0f5-bea7b7fbf704', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11bafa020>]}
23:30:04  Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '0bee3779-05e7-457f-a0f5-bea7b7fbf704', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11bac3970>]}
23:30:04  Found 38 models, 0 tests, 0 snapshots, 0 analyses, 387 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
23:30:04  Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '0bee3779-05e7-457f-a0f5-bea7b7fbf704', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11bd51450>]}
23:30:04  
23:30:04  Acquiring new snowflake connection 'master'
23:30:04  Acquiring new snowflake connection 'list_development_dbt_jyeo'
23:30:04  Using snowflake connection "list_development_dbt_jyeo"
23:30:04  On list_development_dbt_jyeo: /* {"app": "dbt", "dbt_version": "1.5.3", "profile_name": "snowflake", "target_name": "default", "connection_name": "list_development_dbt_jyeo"} */
show terse objects in development.dbt_jyeo
23:30:04  Opening a new connection, currently in state init
23:30:06  SQL status: SUCCESS 10 in 2.0 seconds
23:30:06  On list_development_dbt_jyeo: Close
23:30:06  Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '0bee3779-05e7-457f-a0f5-bea7b7fbf704', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11baf9ea0>]}
23:30:06  Concurrency: 1 threads (target='default')
23:30:06  
23:30:06  Began running node model.my_dbt_project.foo
23:30:06  Re-using an available connection from the pool (formerly list_development_dbt_jyeo, now model.my_dbt_project.foo)
23:30:06  Began compiling node model.my_dbt_project.foo
23:30:06  Writing injected SQL for node "model.my_dbt_project.foo"
23:30:06  Timing info for model.my_dbt_project.foo (compile): 11:30:06.777357 => 11:30:06.781849
23:30:06  Began executing node model.my_dbt_project.foo
23:30:06  Using snowflake connection "model.my_dbt_project.foo"
23:30:06  On model.my_dbt_project.foo: /* {"app": "dbt", "dbt_version": "1.5.3", "profile_name": "snowflake", "target_name": "default", "node_id": "model.my_dbt_project.foo"} */
select '0000-12-30'::date as date_with_zeros
23:30:06  Opening a new connection, currently in state closed
23:30:08  SQL status: SUCCESS 1 in 2.0 seconds
23:30:08  Timing info for model.my_dbt_project.foo (execute): 11:30:06.783848 => 11:30:08.364521
23:30:08  On model.my_dbt_project.foo: Close
23:30:08  Unhandled error while executing 
252005: Failed to convert current row, cause: ordinal must be >= 1
23:30:08  Traceback (most recent call last):
  File "/Users/jeremy/src/dbt-sandcastles/venv_dbt_1.5.latest/lib/python3.10/site-packages/dbt/task/base.py", line 388, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/Users/jeremy/src/dbt-sandcastles/venv_dbt_1.5.latest/lib/python3.10/site-packages/dbt/task/base.py", line 337, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/Users/jeremy/src/dbt-sandcastles/venv_dbt_1.5.latest/lib/python3.10/site-packages/dbt/task/base.py", line 436, in run
    return self.execute(compiled_node, manifest)
  File "/Users/jeremy/src/dbt-sandcastles/venv_dbt_1.5.latest/lib/python3.10/site-packages/dbt/task/show.py", line 28, in execute
    adapter_response, execute_result = self.adapter.execute(
  File "/Users/jeremy/src/dbt-sandcastles/venv_dbt_1.5.latest/lib/python3.10/site-packages/dbt/adapters/base/impl.py", line 289, in execute
    return self.connections.execute(sql=sql, auto_begin=auto_begin, fetch=fetch)
  File "/Users/jeremy/src/dbt-sandcastles/venv_dbt_1.5.latest/lib/python3.10/site-packages/dbt/adapters/snowflake/connections.py", line 438, in execute
    table = self.get_result_from_cursor(cursor)
  File "/Users/jeremy/src/dbt-sandcastles/venv_dbt_1.5.latest/lib/python3.10/site-packages/dbt/adapters/sql/connections.py", line 127, in get_result_from_cursor
    rows = cursor.fetchall()
  File "/Users/jeremy/src/dbt-sandcastles/venv_dbt_1.5.latest/lib/python3.10/site-packages/snowflake/connector/cursor.py", line 1303, in fetchall
    row = self.fetchone()
  File "/Users/jeremy/src/dbt-sandcastles/venv_dbt_1.5.latest/lib/python3.10/site-packages/snowflake/connector/cursor.py", line 1269, in fetchone
    return next(self._result_iterator())
  File "/Users/jeremy/src/dbt-sandcastles/venv_dbt_1.5.latest/lib/python3.10/site-packages/snowflake/connector/cursor.py", line 1246, in _result_iterator
    for _next in self._result:
  File "/Users/jeremy/src/dbt-sandcastles/venv_dbt_1.5.latest/lib/python3.10/site-packages/snowflake/connector/result_set.py", line 68, in result_set_iterator
    yield from first_batch_iter
  File "src/snowflake/connector/arrow_iterator.pyx", line 175, in snowflake.connector.arrow_iterator.PyArrowIterator.__next__
  File "/Users/jeremy/src/dbt-sandcastles/venv_dbt_1.5.latest/lib/python3.10/site-packages/snowflake/connector/errors.py", line 297, in errorhandler_wrapper
    raise Error.errorhandler_make_exception(
snowflake.connector.errors.InterfaceError: 252005: Failed to convert current row, cause: ordinal must be >= 1

23:30:08  Finished running node model.my_dbt_project.foo
23:30:08  Connection 'master' was properly closed.
23:30:08  Connection 'model.my_dbt_project.foo' was properly closed.
23:30:08  Encountered an error:
Runtime Error
  252005: Failed to convert current row, cause: ordinal must be >= 1
23:30:08  Command `dbt show` failed at 11:30:08.961674 after 9.58 seconds
23:30:08  Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1086d1a20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11bdbe4d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1203cc400>]}
23:30:08  Flushing usage events
```

### Environment

```markdown
- OS: macOS-13.4.1-x86_64-i386-64bit
- Python: Python 3.9.13
- dbt-core: 1.5.3
- dbt-snowflake: 1.5.2
```

### Additional Context

I'm not 100% sure why but Snowflake supports dates with year `0000` while something like Postgres will error if you try:

```
Query 1 ERROR: ERROR:  date/time field value out of range: "0000-12-30"
LINE 1: select '0000-12-30'::date as date_with_zeros
```

[Snowflake docs](https://docs.snowflake.com/en/sql-reference/data-types-datetime#date) say:

> For DATE and TIMESTAMP data, Snowflake recommends using years between 1582 and 9999. Snowflake accepts some years outside this range, but years prior to 1582 should be avoided due to [limitations on the Gregorian Calendar](https://docs.snowflake.com/en/sql-reference/data-types-datetime#label-date-types-datetime-supported-calendar).

**Comment by dbeatty10** [comment]
Since Snowflake can handle the year `0000` (and even negative years like `-99999`!) using the same proleptic Gregorian calendar as ISO 8601, I agree that this looks like a bug in snowflake-connector-python.

So I'm going to close this in favor of https://github.com/snowflakedb/snowflake-connector-python/issues/1652
