### ISSUE TITLE
[Bug] Metadata freshness checks that include a filter cause dbt to hang

### ISSUE THREAD

**Issue by sp-tkerlavage** [dbt-labs/dbt-snowflake#831]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I found this when I was testing the new information_schema/metadata driven freshness feature released in v1.7.

I removed the loaded_at field from my freshness test configs and ran them, not realizing I still had a `filter` on my freshness check definition. The output in the terminal showed the freshness checks being executed, but they never completed. Viewing my warehouse query history, I confirmed that dbt didn't actually issue any freshness queries at all.

Removing the `filter` from the freshness check definition resolved the issue.

### Expected Behavior

Metadata driven freshness checks should either support `filter` if theres a use case for that behavior, or `filter` should be ignored and there should be a warning message indicating that `filter` was ignored.

Either way the current behavior where `filter` causes metadata driven freshness checks to just hang does seem to be a bug.

### Steps To Reproduce

This should cause the freshness check to "run" but no query against the warehouse will be issued:
```
version: 2
sources:
  - name: src
    database: db
    schema: test

    tables:
      - name: test_table
        freshness:
          warn_after:
            count: 4
            period: hour
          error_after:
            count: 8
            period: hour
          filter: 1=1
```

This should resolve the error (filter config is removed--freshness check query is actually issued and runs to completion)
```
version: 2
sources:
  - name: src
    database: db
    schema: test

    tables:
      - name: test_table
        freshness:
          warn_after:
            count: 4
            period: hour
          error_after:
            count: 8
            period: hour
```

### Environment

```markdown
- OS: macOS-13.5.2-x86_64-i386-64bit
- Python: 3.11.6
- dbt-core: 1.7.1
- dbt-snowflake: 1.7.0
```

**Comment by dbeatty10** [comment]
Thanks for reporting this @sp-tkerlavage 🙏

I was able to reproduce this in dbt-snowflake and something similar in dbt-postgres as well, so I'm going to transfer this issue to dbt-core.

<details>
<summary>

### Reprex (for Snowflake)
</summary>

`seeds/my_seed.csv`

```csv
id
1
```

Build the seed (to use it as a source):
```shell
dbt seed
```

`models/_sources.yml`
```yaml
version: 2

sources:
  - name: src
    database: "{{ target.database }}"
    schema: "{{ target.schema }}"
    tables:
      - name: my_seed
        freshness:
          warn_after:
            count: 4
            period: hour
          error_after:
            count: 8
            period: hour
          filter: 1=1
```

Let this run for 30 seconds (or whatever) before using ctrl-c to cancel it:
```shell
dbt source freshness
```

Stack trace:
```
05:07:05  1 of 1 START freshness of src.my_seed .......................................... [RUN]
^C05:10:58  CANCEL query source.my_project.src.my_seed ..................................... [CANCEL]
05:10:59  
05:10:59  Exited because of keyboard interrupt
05:10:59  
05:10:59  Done. PASS=0 WARN=0 ERROR=0 SKIP=0 TOTAL=0
05:10:59  Encountered an error:

05:10:59  Traceback (most recent call last):
  File "/Users/dbeatty/projects/environments/snowflake_1.7/lib/python3.10/site-packages/dbt/cli/requires.py", line 90, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/dbeatty/projects/environments/snowflake_1.7/lib/python3.10/site-packages/dbt/cli/requires.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/Users/dbeatty/projects/environments/snowflake_1.7/lib/python3.10/site-packages/dbt/cli/requires.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "/Users/dbeatty/projects/environments/snowflake_1.7/lib/python3.10/site-packages/dbt/cli/requires.py", line 197, in wrapper
    return func(*args, **kwargs)
  File "/Users/dbeatty/projects/environments/snowflake_1.7/lib/python3.10/site-packages/dbt/cli/requires.py", line 244, in wrapper
    return func(*args, **kwargs)
  File "/Users/dbeatty/projects/environments/snowflake_1.7/lib/python3.10/site-packages/dbt/cli/requires.py", line 284, in wrapper
    return func(*args, **kwargs)
  File "/Users/dbeatty/projects/environments/snowflake_1.7/lib/python3.10/site-packages/dbt/cli/main.py", line 846, in freshness
    results = task.run()
  File "/Users/dbeatty/projects/environments/snowflake_1.7/lib/python3.10/site-packages/dbt/task/runnable.py", line 474, in run
    result = self.execute_with_hooks(selected_uids)
  File "/Users/dbeatty/projects/environments/snowflake_1.7/lib/python3.10/site-packages/dbt/task/runnable.py", line 435, in execute_with_hooks
    res = self.execute_nodes()
  File "/Users/dbeatty/projects/environments/snowflake_1.7/lib/python3.10/site-packages/dbt/task/runnable.py", line 359, in execute_nodes
    self.run_queue(pool)
  File "/Users/dbeatty/projects/environments/snowflake_1.7/lib/python3.10/site-packages/dbt/task/runnable.py", line 291, in run_queue
    self.job_queue.join()
  File "/Users/dbeatty/projects/environments/snowflake_1.7/lib/python3.10/site-packages/dbt/graph/queue.py", line 198, in join
    self.inner.join()
  File "/Users/dbeatty/.pyenv/versions/3.10.10/lib/python3.10/queue.py", line 90, in join
    self.all_tasks_done.wait()
  File "/Users/dbeatty/.pyenv/versions/3.10.10/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
KeyboardInterrupt
```
</details>

<details>
<summary>

### Reprex (for Postgres)
</summary>

Everything the same as the reprex for Snowflake above, but doesn't even need the `filter: 1=1` part:

```yaml
version: 2

sources:
  - name: src
    database: "{{ target.database }}"
    schema: "{{ target.schema }}"
    tables:
      - name: my_seed
        freshness:
          warn_after:
            count: 4
            period: hour
          error_after:
            count: 8
            period: hour
```

It should give similar (or same) stacktrace as in Snowflake.
</details>
